# Generated by Django 4.1.6 on 2023-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_addres',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
