# Generated by Django 4.1.6 on 2023-02-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
